app/Http/routes.php
<?php

// Landing
Route::get('/', function () {
	return redirect('/my');
});

Route::get('/account/verify/{token}', 'AccountController@getDoVerify');						// Verify user account
Route::post('/billing/vt/callback', 'BillingController@vtNotification');					// Veritrans callback

// CSRF protection, sessions, cookies, etc..
Route::group(['middlewareGroups' => ['web']], function ()
{
	// Authentication / Registration
	Route::get('/recover', 'Auth\PasswordController@getEmail');								// Forgot password form
	Route::get('/login', 'Auth\AuthController@showLoginForm');								// Login form
	Route::get('/logout', 'Auth\AuthController@logout');									// Logout action
	Route::get('/oauth/{provider}', 'Auth\AuthController@redirectToProvider');				// 3rd-party OAuth redirect
	Route::get('/oauth/callback/{provider}', 'Auth\AuthController@handleProviderCallback');	// 3rd-party OAuth callback
	Route::get('/register', 'Auth\AuthController@getRegister');								// New user registration form
	Route::get('/reset/{token}', 'Auth\PasswordController@getReset');						// Forgot password reset form
	Route::post('/recover', 'Auth\PasswordController@postEmail');							// Forgot password action
	Route::post('/register', 'Auth\AuthController@postRegister');							// New user registration action
	Route::post('/reset', 'Auth\PasswordController@postReset');								// Forgot password reset action

	Route::group(['middleware' => ['cors']], function ()
	{
		Route::post('/login', 'Auth\AuthController@postLogin');								// Login action
	});

	// Authenticated area
	Route::group(['middleware' => ['auth']], function ()
	{
	    Route::get('/my', 'AccountController@getHome');										// Profile home
	    Route::get('/my/invoices/{orderNo}', 'BillingController@getInvoice');				// View printable invoice
	    Route::get('/my/settings', 'AccountController@getSettings');						// View general settings form
	    Route::get('/my/settings/accounts', 'AccountController@getConnectedAccounts');		// List all connected accounts
	    Route::get('/my/settings/billing', 'AccountController@getBilling');					// View billing data form
		Route::get('/my/settings/password', 'AccountController@getPassword');				// View password change form
		Route::get('/my/subscriptions', 'SubscriptionController@getList');					// List all subscriptions
	    Route::post('/my/settings', 'AccountController@postSettings');						// general settings form action
	    Route::post('/my/settings/billing', 'AccountController@postBilling');				// Post billing data action
	    Route::post('/my/settings/password', 'AccountController@postPassword');				// Password change form action
		
	    Route::get('/account/verify', 'AccountController@getVerify');						// Initiate user account verification
	    Route::get('/order/confirm', 'BillingController@getOrderConfirm');					// View payment confirmation form
		Route::get('/subscribe', 'SubscriptionController@getSubscribe');					// Subscription checkout page
	    Route::post('/order/confirm', 'BillingController@postOrderConfirm');				// Payment confirmation form action
		Route::post('/subscribe', 'BillingController@postSubscribe');						// Initiate subscription order
		
		// Admin routes
		Route::group(['prefix' => 'orders'], function ()
		{
			Route::get('/all', 'Admin\OrderController@getList');							// List all subscription
			Route::get('/confirmations/all', 'Admin\OrderController@getConfirmationsList');	// List all payment confirmation
			Route::get('/invoices/{orderNo}', 'BillingController@getInvoice');				// View printable invoice
			Route::get('/{orderNo}', 'Admin\OrderController@getSingle');					// View single order
			Route::post('/action/{action}', 'Admin\OrderController@postAction');			// Subscription order action
			Route::delete('/confirmations', 'Admin\OrderController@deleteConfirmation');	// Delete a single payment confirmation
		});
		Route::group(['prefix' => 'users'], function ()
		{
			Route::get('/all', 'Admin\UserController@getList');								// List all registered accounts
			Route::get('/groups/all', 'Admin\UserGroupController@getList');					// List all account groups
			Route::get('/groups/create', 'Admin\UserGroupController@getCreate');			// New account group form
			Route::get('/groups/{name}', 'Admin\UserGroupController@getSingle');			// View single account group
			Route::get('/groups/{name}/subscribe', 'Admin\UserGroupController@getSubscribe');	// Create subscription for group form
			Route::get('/register', 'Admin\UserController@getCreate');						// New account registration form
			Route::get('/{email}', 'Admin\UserController@getEdit');							// View and edit existing account
			Route::get('/{email}/subscribe', 'Admin\UserController@getSubscribe');			// Create subscription for account form
			Route::post('/deactivate', 'Admin\UserController@getDeactivate');				// Deactivate account action
			Route::post('/edit', 'Admin\UserController@postEdit');							// Edit existing account action
			Route::post('/register', 'Admin\UserController@postCreate');					// New account registration action
			Route::post('/subscribe', 'Admin\UserController@postSubscribe');				// Create subscription for account action
			Route::post('/groups/subscribe', 'Admin\UserGroupController@postSubscribe');	// Create subscription for group members action
			Route::delete('/groups/{name}', 'Admin\UserGroupController@deleteSingle');		// Delete a single account group
		});
		Route::group(['prefix' => 'roles'], function ()
		{
			Route::get('/all', 'Admin\RoleController@getList');								// List all application roles
			Route::get('/create', 'Admin\RoleController@getCreate');						// New application role form
			Route::get('/{roleId}', 'Admin\RoleController@getEdit');						// Edit existing role
			Route::post('/create', 'Admin\RoleController@postCreate');						// New application role action
			Route::post('/{roleId}', 'Admin\RoleController@postEdit');						// Edit existing role action
		});
	});

	// API
	Route::group(['prefix' => 'api', 'middleware' => ['api', 'cors']], function ()
	{
		Route::get('/status', 'API\AccountController@getStatus');
		Route::get('/available-topics', 'API\AccountController@getTopics');
		Route::post('/subscribe-email', 'API\EmailSubscriptionController@postSubscribe');

		Route::group(['middleware' => 'auth'], function ()
		{
			Route::get('/users/search', 'API\UserController@getSearch');
			Route::get('/users/user-group/{group}', 'API\UserController@getListByUserGroup');
			Route::post('/users/user-group/{group}/{action}', 'API\UserController@postUserGroupAction');
			Route::post('/user-groups/save', 'API\UserGroupController@postSave');
		});
	});
	
});

// Testing
Route::group(['prefix' => 'test'], function ()
{
	Route::get('/curl', 'TestController@curl');
	Route::get('/email/{view}', 'TestController@getEmail');
	Route::get('/email', function ()
	{
		if (env('TEST_EMAIL', null) == null)
			return abort(403);
		Mail::queue('emails.id.welcome', ['user' => \App\User::find(1)], function ($m)
        {
            $m->from('support@gakken-idn.co.id', 'Gakken Support');
            $m->to(env('TEST_EMAIL', "endy.hardy@gakken-idn.co.id"), "Endy Hardy")->subject("This is a Test Message via Mailgun Sandbox");
        });

        return "Email sent";
	});
});

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;

class UserController extends Controller
{
    public function getSearch(Request $request)
    {
    	return $request->term ? 
    		User::where('name', 'like', '%' . $request->term . '%')
    			->orWhere('email', 'like', '%' . $request->term . '%')
    			->get()
    			->toJson() :
    		abort(404);
    }

    public function getListByUserGroup(Request $request, $group)
    {
    	$group = \App\UserGroup::where('slug', $group)->with('adminUser')->firstOrFail();
    	$members = $request->term ?
    		$group->members()->where('name', 'like', '%' . $request->term . '%')
    			->where('email', 'like', '%' . $request->term . '%')
                ->get() :
    		$group->members()->get();

        foreach ($members as $member) {
            $member->pivot->created_at_label = date(date('Ymd', strtotime($member->pivot->created_at)) == date('Ymd') ? 'g:i a' : 'j M y', strtotime($member->pivot->created_at));
        }
        $group->members = $members;
        return $group->toJson();
    }

    public function postUserGroupAction(Request $request, $group, $action)
    {
        if (!in_array($action, ['add', 'remove', 'adminize'])) abort(404);
        $this->authorize('general', 'accounts.user_groups.manage');

        $user = User::where('email', $request->input('email'))->firstOrFail();
        $group = \App\UserGroup::where('slug', $group)->firstOrFail();

        switch ($action) {
            case 'add': $group->members()->attach($user); break;
            case 'remove': $group->members()->detach($user); break;
            case 'adminize': 
                $group->admin_id = $user->id;
                $group->save();
        }

        return json_encode(['status' => 'success']);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use App\UserSubscription;
use Mail;

class UserController extends Controller
{
    public function getCreate()
    {
    	$this->authorize('general', 'accounts.users.create');
    	return view('users.form', ['user' => new User]);
    }

    public function getEdit($email)
    {
        $this->authorize('general', 'accounts.users.edit');
        $user = User::where('email', $email)->firstOrFail();
        if ($user->role->is_super)
            return app()->abort(404);
        $user->role = $user->role_id;
        return view('users.form', [
            'user'          => $user,
            'subscription'  => $user->currentSubscription(),
            'orders'        => $user->subscriptionOrders,
            ]);
    }

    public function getList(Request $request)
    {
        $this->authorize('general', 'accounts.users.view');
        $users = $request->s ?
            User::where('name', 'like', '%' . $request->s . '%')
                ->orWhere('email', 'like', '%' . $request->s . '%')
                ->withCount('userGroups')
                ->paginate(15):
            User::withCount('userGroups')->paginate(15);
        return view('users.list')->with(['users' => $users]);
    }

    public function getSubscribe(Request $request, $email)
    {
        $this->authorize('general', 'accounts.users.subscription.subscribe');
        $user = User::where('email', $email)->firstOrFail();
        return view('users.form_subscribe')->with(['user' => $user]);
    }

    public function postCreate(Request $request)
    {
    	$this->authorize('general', 'accounts.users.create');
    	$this->validate($request, [
    		'email'					=> 'required|email|max:255',
            'password'              => 'required|min:8|max:255|confirmed',
            'name'                  => 'required|max:255',
            'role'                  => 'required|integer|exists:roles,id',
            'autoverify'            => 'boolean',
            'send_welcome_email'    => 'boolean',
            'redirect'              => 'in:list,home'
            ]);

        $user = new User;
        $user->email    = $request->email;
        $user->password = bcrypt($request->password);
        $user->name     = $request->name;
        $user->role_id  = $request->role;
        $user->save();
        $user->toMoodleUser();

        if ($request->send_welcome_email) {
            Mail::queue('emails.welcome', ['user' => $user], function ($m) use ($user)
            {
                $m->from('support@gakken-idn.co.id', 'Gakken Support');
                $m->to($user->email, $user->name)->subject(trans('account.emails.welcome'));
            });
        }

        if ($request->autoverify) 
            $user->verify();
        else {
            $verifyToken = $user->initVerify();
            Mail::queue('emails.' . app()->getLocale() . '.account_verify', ['user' => $user, 'token' => $verifyToken], function ($m) use ($user)
            {
                $m->from('support@gakken-idn.co.id', 'Gakken Support');
                $m->to($user->email, $user->name)->subject(trans('account.emails.verify_progress'));
            });
        }

        $request->session()->flash('msg-success', trans('admin.users.register.messages.success_new'));
        switch ($request->redirect) {
            case 'list': $redirect = '/users/all'; break;
            default: $redirect = '/my';
        }
        return redirect($redirect);
    }

    public function postEdit(Request $request)
    {
        $this->authorize('general', 'accounts.users.edit');
        $this->validate($request, [
            'email'         => 'required|exists:users,email',
            'name'          => 'required|max:255',
            'password'      => 'confirmed|min:8',
            'role'          => 'required|integer|exists:roles,id',
            'autoverify'    => 'boolean',

            'profession'    => 'in:doctor,dentist',
            'id_no'         => 'required_with:profession|max:24',
            'address_1'     => 'required_with:address_2|max:255',
            'address_2'     => 'max:255',
            'city'          => 'max:255',
            'postal_code'   => 'max:6',
            'phone'         => 'max:13',
            'country'       => 'max:3',
            ]);

        $user = User::where('email', $request->email)->firstOrFail();
        $user->name     = $request->name;
        $user->role_id  = $request->role;
        if ($request->password) {
            $user->password = bcrypt($request->password);
            $user->is_provider = false;
        }
        $user->profession = $request->profession ?: null;
        $user->id_no = $request->id_no ?: null;
        $user->save();

        $detail = $user->userDetail ?: new \App\UserDetail;
        $detail->user_id = $user->id;
        $detail->address_1 = $request->address_1;
        $detail->address_2 = $request->address_2;
        $detail->city = $request->city;
        $detail->postal_code = $request->postal_code;
        $detail->phone = $request->phone;
        $detail->country_code = $request->country;
        $detail->save();

        if ($request->autoverify)
            $user->verify();

        $request->session()->flash('msg-success', trans('admin.users.register.messages.success_edit'));
        return redirect('users/all');
    }

    public function postSubscribe(Request $request)
    {
        $this->authorize('general', 'accounts.users.subscription.subscribe');
        $this->validate($request, [
            'email'         => 'required|exists:users,email',
            'fixed_dates'   => 'boolean',
            'starts_at'     => 'required_with:fixed_dates|date|after:yesterday',
            'expired_at'    => 'required_with:fixed_dates|date|after:starts_at',
            'duration'      => 'required_without:fixed_dates|integer',
            'period'        => 'required_without:fixed_dates|in:days,weeks,months,years'
            ]);

        $user = User::where('email', $request->email)->firstOrFail();
        $subscription = \App\Subscription::where('is_custom', true)->firstOrFail();
        $currentSubscription = $user->currentSubscription();
        $userSubscription = new UserSubscription;
        $userSubscription->user_id = $user->id;
        $userSubscription->subscription_id = $subscription->id;
        
        if ($request->fixed_dates) {
            $userSubscription->starts_at = strtotime($request->starts_at);
            $userSubscription->expired_at = strtotime($request->expired_at);
        } else {
            $startDate = $currentSubscription ? strtotime($currentSubscription->expired_at) : time();
            $userSubscription->starts_at = $startDate;
            $userSubscription->expired_at = strtotime('+' . $request->duration . ' ' . $request->period, $startDate);
        }
        $userSubscription->save();

        $request->session()->flash('msg-success', trans('admin.users.subscribe.messages.success_new'));
        return redirect('/users/' . urlencode($user->email));
    }
}

resources/views/users/form.blade.php
@extends('layout.user')

@section('title') {{ trans('app.page_title', ['title' => trans('admin.users.register.title_' . ($user->id ? 'edit' : 'new'))]) }} @endsection

@section('stylesheets')

	<link rel="stylesheet" type="text/css" href="{{ asset('/bower_components/Strength.js/src/strength.css') }}" />
	<style type="text/css">
		[name=password] { border-bottom-left-radius: 0; border-bottom-right-radius: 0; }
		.button_strength { display: none; }
		.strength_meter { float: left; width:100%; }
	</style>

@endsection

@section('user-content')

	@include('layout.alert')

	<h2>{{ trans('admin.users.register.title_' . ($user->id ? 'edit' : 'new')) }}</h2>

	{!! Form::model($user, ['url' => '/users/' . ($user->id ? 'edit' : 'register'), 'class' => 'form-horizontal']) !!}

		@if (Request::input('ref'))
			{!! Form::hidden('redirect', Request::input('ref')) !!}
		@endif
		<div class="form-group">
			<label class="control-label col-lg-3 col-sm-4">{{ trans('admin.users.register.fields.email') }}</label>
			@if ($user->id)
				<div class="col-lg-8">
					{!! Form::hidden('email') !!}
					<p class="form-control-static">{{ $user->email }}</p>
				</div>
			@else
				<div class="col-lg-8">
					{!! Form::email('email', null, ['class' => 'form-control']) !!}
				</div>
			@endif
		</div>

		<div class="form-group">
			<label class="control-label col-lg-3 col-sm-4">{{ trans('admin.users.register.fields.name') }}</label>
			<div class="col-lg-8">{!! Form::text('name', null, ['class' => 'form-control']) !!}</div>
		</div>
		<div class="form-group">
			<label class="control-label col-lg-3 col-sm-4">{{ trans('admin.users.register.fields.password_' . ($user->id ? 'change' : 'new')) }}</label>
			<div class="col-lg-4">{!! Form::password('password', ['class' => 'form-control', 'id' => 'password']) !!}</div>
		</div>
		<div class="form-group">
			<label class="control-label col-lg-3 col-sm-4">{{ trans('admin.users.register.fields.password_confirmation') }}</label>
			<div class="col-lg-4">{!! Form::password('password_confirmation', ['class' => 'form-control']) !!}</div>
		</div>
		<div class="form-group">
			<label class="control-label col-lg-3 col-sm-4">{{ trans('admin.users.register.fields.role') }}</label>
			<div class="col-lg-8">{!! Form::select('role', \App\Role::dropdown(), $user->role_id ?: 3, ['class' => 'form-control']) !!}</div>
		</div>

		<div class="form-group">
			@if (!$user->verified_at)
				<div class="col-lg-8 col-lg-offset-4">
					<div class="checkbox">
						<label>{!! Form::checkbox('autoverify') !!} {{ trans('admin.users.register.fields.autoverify') }}</label>
					</div>
				</div>
			@endif

			@if (!$user->id)
				<div class="col-lg-8 col-lg-offset-4">
					<div class="checkbox">
						<label>{!! Form::checkbox('send_welcome_email') !!} {{ trans('admin.users.register.fields.send_welcome_email') }}</label>
					</div>
				</div>
			@endif
		</div>

		@if ($user->id)
			<!-- PROFESSIONAL DETAILS -->
			<h4 class="page-header" style="margin-top:30px;margin-bottom:15px;">{{ trans('admin.users.register.prof_details') }}</h4>
			<div class="form-group">
				<label class="col-lg-3 col-sm-4 control-label">Profession</label>
				<div class="col-lg-8">
					<div class="radio">
						<label>{!! Form::radio('profession', 'doctor', $user->profession == 'doctor') !!} Doctor</label>&ensp;
						<label>{!! Form::radio('profession', 'dentist', $user->profession == 'dentist') !!} Dentist</label>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 col-sm-4 control-label">IDI/PDGI No.</label>
				<div class="col-lg-4">
					{!! Form::text('id_no', $user->id_no ?: null, ['class' => 'form-control']) !!}
				</div>
			</div>

			<!-- BILLING DETAILS -->
			<h4 class="page-header" style="margin-top:30px;margin-bottom:15px;">{{ trans('admin.users.register.billing_details') }}</h4>
			<div class="form-group">
				<label class="control-label col-lg-3 col-sm-4">{{ trans('account.settings.billing.address_1') }}</label>
				<div class="col-lg-8"> 
					{!! Form::text('address_1', $user->userDetail ? $user->userDetail->address_1 : null, ['class' => 'form-control']) !!}
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-lg-3 col-sm-4">{{ trans('account.settings.billing.address_2') }}</label>
				<div class="col-lg-8"> 
					{!! Form::text('address_2', $user->userDetail ? $user->userDetail->address_2 : null, ['class' => 'form-control']) !!}
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-lg-3 col-sm-4">{{ trans('account.settings.billing.city') }}</label>
				<div class="col-lg-4"> 
					{!! Form::text('city', $user->userDetail ? $user->userDetail->city : null, ['class' => 'form-control']) !!}
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-lg-3 col-sm-4">{{ trans('account.settings.billing.postal_code') }}</label>
				<div class="col-lg-4"> 
					{!! Form::text('postal_code', $user->userDetail ? $user->userDetail->postal_code : null, ['class' => 'form-control']) !!}
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-lg-3 col-sm-4">{{ trans('account.settings.billing.phone') }}</label>
				<div class="col-lg-4"> 
					{!! Form::text('phone', $user->userDetail ? $user->userDetail->phone : null, ['class' => 'form-control']) !!}
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-lg-3 col-sm-4">{{ trans('account.settings.billing.country_code') }}</label>
				<div class="col-lg-4"> 
					{!! Form::select('country', ['IDN' => 'Indonesia'], $user->userDetail ? $user->userDetail->country_code : null, ['class' => 'form-control']) !!}
				</div>
			</div>

			<!-- CURRENT SUBSCRIPTION -->
			<h4 class="page-header" style="margin-top:30px;margin-bottom:15px;">{{ trans('admin.users.register.subscription') }}</h4>
			@if ($subscription)
				<p>{{ trans('subscription.has_subscription', ['expire' => date('j M Y', strtotime($subscription->expired_at))]) }}</p>
			@else
				<p>
					{{ trans('admin.users.register.not_subscribed') }}
					<a href="/users/{!! urlencode($user->email) !!}/subscribe">{{ trans('admin.users.register.action.subscribe') }}</a>
				</p>
			@endif

			<!-- ORDER HISTORY -->
			<h4 class="page-header" style="margin-top:30px;margin-bottom:15px;">{{ trans('subscription.self.orders.title') }}</h4>
			@if (count($orders) > 0)
				<table class="table table-condensed">
					<thead>
						<tr>
							<th style="width:150px;">{{ trans('subscription.self.orders.order_no') }}</th>
							<th>{{ trans('subscription.self.orders.subscription') }}</th>
							<th class="text-right">{{ trans('subscription.self.orders.total') }}</th>
							<th>{{ trans('subscription.self.orders.status') }}</th>
						</tr>
					</thead>
					<tbody>
						@foreach($orders as $order)
							<tr>
								<td><a href="/orders/{{ $order->order_no }}?ref=account">{{ $order->order_no }}</td>
								<td>{{ $order->subscription->label }}</td>
								<td class="text-right">IDR {{ number_format($order->total, 0, '.', ',') }}</td>
								<td>
									{{ trans('subscription.order.status.' . $order->status) }}
									({{ trans('subscription.subscribe.payment_method.' . $order->method) }})
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			@else
				<p>{{ trans('admin.users.register.orders_empty') }}</p>
			@endif

		@endif

		<div style="margin-top:30px;">
			<button type="submit" class="btn btn-default">{{ trans('admin.users.register.fields.submit_' . ($user->id ? 'change' : 'new')) }}</button>
			<button type="button" class="btn" id="deactivateBtn" data-toggle="modal" data-target="#deactivateModal">{{ trans('account.action.deactivate') }}</button>
		</div>

		<p style="margin-top: 30px;">
			@if (Request::input('ref') == 'list')
				<a href="/users/all">{{ trans('admin.users.action.back_list') }}</a>
			@else
				<a href="/my">{{ trans('account.action.home') }}</a>
			@endif
		</p>

	{!! Form::close() !!}

@endsection

@section('scripts')
	<script type="text/javascript" src="{{ asset('/bower_components/Strength.js/src/strength.min.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$("#password").strength();
		});
	</script>

@endsection

resources/views/users/list.blade.php
@extends('layout.user')

@section('title') {{ trans('app.page_title', ['title' => trans('admin.users.list.title')]) }} @endsection

@section('user-content')

	@include('layout.alert')

	<h2>{{ trans('admin.users.list.title') }}</h2>

	<div style="margin-bottom:15px;">
		<span class="pull-left">
			<a href="/users/register?ref=list" class="btn btn-primary">
				{{ trans('admin.users.register.title_new') }}
			</a>
		</span>
		{!! Form::open(['url' => '/users/all', 'class' => 'form-inline pull-right', 'method' => 'get']) !!}
			@if (count($users))
				<label class="control-label">
					{{ trans('app.pagination', ['first' => $users->firstItem(), 'last' => $users->lastItem(), 'total' => $users->total()]) }}
				</label>
			@endif
			<div class="input-group">
				{!! Form::text('s', Request::input('s'), ['class' => 'form-control', 'placeholder' => trans('admin.users.list.search')]) !!}
				<span class="input-group-btn">
					<button type="submit" class="btn btn-default">Go</button>
				</span>
			</div>
		{!! Form::close() !!}
		<div class="clearfix"></div>
	</div>

	@if (count($users) > 0)
		<table class="table table-hover table-bordered">
			<thead>
				<tr>
					<th>{{ trans('admin.users.list.email') }}</th>
					<th>{{ trans('admin.users.list.name') }}</th>
					<th>{{ trans('admin.users.list.groups') }}</th>
					<th>{{ trans('admin.users.list.created_at') }}</th>
					<th>{{ trans('admin.users.list.status') }}</th>
				</tr>
			</thead>
			<tbody>
				@foreach($users as $user)
					<tr>
						<td>
							@if (!$user->role->is_super)
							<a href="/users/{{ urlencode($user->email) }}?ref=list">{{ $user->email }}</a>
							@else
								{{ $user->email }}
							@endif
						</td>
						<td>{{ $user->name }}</td>
						<td>{{ $user->user_groups_count ?: trans('account.no_group') }}</td>
						<td>{{ $user->created_at }}</td>
						<td>
							{{ trans('account.status.' . $user->getStatus()) }}
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>

		{!! $users->appends(['s' => Request::input('s')])->links() !!}
	@else
		<p>{{ trans('admin.users.list.empty') }}</p>
	@endif

	<p>
		<a href="/my">{{ trans('account.action.home') }}</a>
	</p>

@endsection